"""
matching_tool.py
----------------
SmartPay AP - D2 Matching Model as Agent Tool

Wraps the D2 matching model as a callable tool
that the LangGraph agent can invoke.

Why separate file:
    Single responsibility — only matching logic.
    No imports from our other files.
    Can be tested independently.
    Can be replaced with API call in production.
"""

import os
import pandas as pd

# Path to labeled dataset generated by D2 notebook
BASE_DIR     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR     = os.path.join(BASE_DIR, "data")
LABELED_FILE = os.path.join(DATA_DIR, "labeled_dataset.csv")

PRICE_TOLERANCE = 0.01  # 1% price deviation allowed


def matching_tool(invoice_id: str) -> dict:
    """
    Calls D2 matching model as an agent tool.

    Checks invoice against PO and GRN records.
    Returns match result with mismatch details.

    Args:
        invoice_id: e.g. "INV0002"

    Returns:
        {
            "match_result": "MATCH" or "MISMATCH",
            "mismatches":   [...],
            "summary":      "..."
        }

    Guardrail:
        Validates invoice_id before processing.
        Rejects invalid inputs immediately.
    """

    # Input validation guardrail
    if not invoice_id or not isinstance(invoice_id, str):
        return {
            "match_result": "ERROR",
            "mismatches":   [],
            "summary":      "Invalid invoice_id passed to matching tool."
        }

    # Load dataset
    try:
        df = pd.read_csv(LABELED_FILE)
    except FileNotFoundError:
        return {
            "match_result": "ERROR",
            "mismatches":   [],
            "summary":      "Dataset not found. Run D2 notebook first."
        }

    # Look up invoice
    lookup_id = invoice_id.replace("_DUP", "")
    rows      = df[df["invoice_id"] == lookup_id]

    if rows.empty:
        return {
            "match_result": "NOT_FOUND",
            "mismatches":   [],
            "summary":      f"Invoice {invoice_id} not found."
        }

    mismatches = []

    for _, row in rows.iterrows():

        # Rule 1: Quantity mismatch
        if row["quantity"] != row["po_quantity"]:
            mismatches.append({
                "line":   int(row["line_item_number"]),
                "item":   row["item_code"],
                "type":   "QUANTITY_MISMATCH",
                "detail": f"Invoice qty={row['quantity']}, "
                          f"PO qty={row['po_quantity']}"
            })

        # Rule 2: Price mismatch
        price_diff_pct = abs(
            row["unit_price"] - row["po_unit_price"]
        ) / (row["po_unit_price"] + 1e-9)

        if price_diff_pct > PRICE_TOLERANCE:
            mismatches.append({
                "line":   int(row["line_item_number"]),
                "item":   row["item_code"],
                "type":   "PRICE_MISMATCH",
                "detail": f"Invoice price={row['unit_price']}, "
                          f"PO price={row['po_unit_price']}"
            })

        # Rule 3: GRN not received
        if row["grn_quantity"] == 0:
            mismatches.append({
                "line":   int(row["line_item_number"]),
                "item":   row["item_code"],
                "type":   "GRN_NOT_RECEIVED",
                "detail": "Goods not received yet."
            })

        # Rule 4: Duplicate invoice
        if "_DUP" in str(invoice_id):
            mismatches.append({
                "line":   int(row["line_item_number"]),
                "item":   row["item_code"],
                "type":   "DUPLICATE_INVOICE",
                "detail": "Duplicate invoice submission detected."
            })

    match_result = "MISMATCH" if mismatches else "MATCH"

    if match_result == "MATCH":
        summary = (
            f"Invoice {invoice_id}: "
            f"All lines match PO and GRN."
        )
    else:
        lines = [
            f"  Line {m['line']} ({m['item']}): "
            f"{m['type']} — {m['detail']}"
            for m in mismatches
        ]
        summary = (
            f"Invoice {invoice_id}: "
            f"{len(mismatches)} mismatch(es) found.\n"
            + "\n".join(lines)
        )

    return {
        "match_result": match_result,
        "mismatches":   mismatches,
        "summary":      summary
    }
